cabal-version: 2.2
name: rethinkdb
version: 2.2.0.10
build-type: Custom
license: Apache-2.0
license-file: LICENSE
maintainer: Etienne Laurin <etienne@atnnn.com>
homepage: http://github.com/atnnn/haskell-rethinkdb
synopsis: A driver for RethinkDB 2.2
description:
    A driver for the RethinkDB database server
category: Database
author: Etienne Laurin, Brandon Martin

tested-with:
  GHC==7.6.3,
  GHC==7.8.4,
  GHC==7.10.3,
  GHC==8.0.2

custom-setup
    setup-depends:
        base >= 4 && <5,
        Cabal >= 2.0,
        cabal-doctest >= 1.0.9

source-repository head
    type: git
    location: https://github.com/atnnn/haskell-rethinkdb

flag dev
    default: False
    manual: True

common common
    default-language: Haskell2010

library
    import: common
    build-depends:
        base >=4 && <4.20,
        unordered-containers ==0.2.*,
        text >=2.0 && <2.2,
        aeson >=2.0.0.0 && <2.3,
        bytestring ==0.12.*,
        containers >=0.6 && < 0.9,
        data-default >=0.7 && <0.9,
        network >=3.2 && <3.3,
        network-bsd >= 2.8 && < 3,
        mtl >=2.1 && <2.4,
        vector >=0.10 && <0.14,
        time >=1.9 && <2,
        utf8-string >=0.3 && <1.1,
        binary >=0.5 && <0.9,
        scientific ==0.3.*,
        base64-bytestring ==1.2.*

    if flag(dev)
        other-modules:
            Debug
        exposed: True
        buildable: True
        -- ghc-prof-options: -fprof-auto
    exposed-modules:
        Database.RethinkDB
        Database.RethinkDB.NoClash
        Database.RethinkDB.Driver
        Database.RethinkDB.Functions
        Database.RethinkDB.Time
        Database.RethinkDB.Types
        Database.RethinkDB.Datum
        Database.RethinkDB.Geospatial
        Database.RethinkDB.ReQL
        Database.RethinkDB.Network
        Database.RethinkDB.MapReduce
        Database.RethinkDB.Wire
        Database.RethinkDB.Wire.Datum
        Database.RethinkDB.Wire.Frame
        Database.RethinkDB.Wire.Query
        Database.RethinkDB.Wire.Response
        Database.RethinkDB.Wire.Term
        Database.RethinkDB.Wire.VersionDummy
        Database.RethinkDB.Doctest
    exposed: True
    buildable: True

    if impl(ghc > 8)
        ghc-options: -Wall -Wno-redundant-constraints
    else
        ghc-options: -Wall

test-suite doctests
    import: common
    build-depends:
        base,
        doctest >=0.9,
        cabal-doctest >=1.0.9,
        rethinkdb
    type: exitcode-stdio-1.0
    main-is: doctests.hs
    buildable: True
    ghc-options: -threaded

benchmark bench
    import: common
    build-depends:
        base,
        criterion,
        rethinkdb,
        text,
        aeson,
        async
    hs-source-dirs: bench
    type: exitcode-stdio-1.0
    main-is: Bench.hs
    ghc-options: -O2 -threaded -rtsopts -with-rtsopts=-N
    ghc-prof-options: "-with-rtsopts=-p -s -h -i0.1 -N"

executable proto2hs
  import: common
  if !flag(dev)
    buildable: False
  main-is: proto2hs.hs
  build-depends: base, text, attoparsec
